// flow-typed signature: bb2fc737595209ffe26364866a89d2f9
// flow-typed version: <<STUB>>/uniqid_v^5.0.3/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *
 *   'uniqid'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'uniqid' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'uniqid/index' {
  declare module.exports: $Exports<'uniqid'>;
}
declare module 'uniqid/index.js' {
  declare module.exports: $Exports<'uniqid'>;
}
